global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scienchan-backend'
    scrape_interval: 5s
    # Scrape localhost if running on host, or container name if in docker
    # Using host.docker.internal for Mac/Windows, or 172.17.0.1 for Linux
    # reliable approach for Linux is often --add-host host.docker.internal:host-gateway
    static_configs:
      - targets: ['host.docker.internal:8000']
